# Generated by Django 3.0.8 on 2020-07-26 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Included',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=4000)),
                ('hidden', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_address', models.CharField(max_length=4000)),
                ('file_hash', models.CharField(max_length=1000)),
                ('included', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.Included')),
            ],
        ),
    ]
