# Generated by Django 3.0.8 on 2020-07-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Included',
            new_name='Storage',
        ),
    ]
