# Generated by Django 3.0.8 on 2020-07-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_storage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='full_address',
            field=models.FilePathField(),
        ),
        migrations.AlterField(
            model_name='storage',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True),
        ),
    ]
