# Generated by Django 3.0.8 on 2020-07-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_auto_20200726_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='/', recursive=True),
        ),
    ]
