# Generated by Django 3.0.8 on 2020-07-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0006_auto_20200726_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='path',
            field=models.CharField(max_length=4000),
        ),
    ]
