# Generated by Django 3.0.8 on 2020-07-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0007_auto_20200726_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='full_address',
            new_name='path',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='included',
            new_name='storage',
        ),
        migrations.AlterField(
            model_name='storage',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
