# Generated by Django 3.0.8 on 2020-07-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0008_auto_20200726_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(max_length=4000),
        ),
    ]
