# Generated by Django 3.0.8 on 2020-08-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0011_file_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
