# Generated by Django 3.0.8 on 2020-08-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0012_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
